services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
        - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    environment: 
      - MONGODB_URL=mongodb://mongodb:27017/blog
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo 
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:

